# f = open('python.txt', 'w')
# f.write("This is an introductory Python class.\n")
# f.write("This is  CPGM 6340.")
# f = open('python.txt', 'r')
# print(f.read())
# f=open("python.txt","a")
# f.write("The instructor is Vinita")
# f = open('python.txt', 'r')
# print(f.read())
# f=open('python.txt','w')
# # # f.write("additional text")
# f.write("123")
# f.write('esfe"')
# f=open('python.txt','r')
# print(f.read())

# f = open('python.txt', 'w+')
# f.write("This is Beginning programming 1 class.\n")
# f.write("The class timings are Monday 6.30 pm to 8.30 pm\n")
# f.seek(0)
# print(f.read())
# f.close()
# f = open('python.txt', 'w')
# f = open('python.txt', 'r+')
# f.write("I love programming!")
# #file pointer at end and so 
# f.seek(0)
# print(f.read())
# f.close()
# import os
# os.remove("python.txt")
# f = open('python.txt', 'w')
# f.write("Hi!How are you \n")
# f.write("are you in town today?")
# f = open('python.txt', 'a+')
# f.write("ByeBye")
# f.seek(0)
# print(f.read())
# f.close()

f = open('python.txt', 'w')
f.write("This is an introductory Python class.\n")
f.write("This is  CPGM 6340.")
f = open('python.txt', 'a')
f.write("ByeBye")
f = open('python.txt', 'r')
print(f.read())
